### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'id')

### ISSUE THREAD

**Issue by 8fn** [8fn/BrowseMuscle#13]
TypeError: Cannot read properties of undefined (reading 'id')
    at alterar (C:\Users\tanjil\Desktop\PAP\src\controllers\ExercicioController.js:66:28)
    at Layer.handle [as handle_request] (C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\index.js:284:15
    at param (C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\index.js:365:14)
    at param (C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\index.js:376:14)
    at Function.process_params (C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\index.js:421:3)
    at next (C:\Users\tanjil\Desktop\PAP\node_modules\express\lib\router\index.js:280:10)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by 8fn** [comment]
```js
let id = req.params.nome.id;
```
TO
```js
let id = req.params.id;
```
