### ISSUE TITLE
🐛 Error: data and hash arguments required

### ISSUE THREAD

**Issue by 8fn** [8fn/BrowseMuscle#174]
Ao introduzir os credenciais com um utilizador que não exista na base de dados

**Comment by 8fn** [comment]
```
Error: data and hash arguments required
    at Object.compare (/home/tanjil/Desktop/BrowseMuscle/node_modules/bcrypt/bcrypt.js:208:17)
    at /home/tanjil/Desktop/BrowseMuscle/node_modules/bcrypt/promises.js:29:12
    at new Promise (<anonymous>)
    at Object.module.exports.promise (/home/tanjil/Desktop/BrowseMuscle/node_modules/bcrypt/promises.js:20:12)
    at Object.compare (/home/tanjil/Desktop/BrowseMuscle/node_modules/bcrypt/bcrypt.js:204:25)
    at Strategy.authenticateUser [as _verify] (/home/tanjil/Desktop/BrowseMuscle/src/passport-config.js:13:29)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
