### ISSUE TITLE
Cannot delete or update a parent row: a foreign key constraint fails

### ISSUE THREAD

**Issue by 8fn** [8fn/BrowseMuscle#49]
sqlMessage: 'Cannot delete or update a parent row: a foreign key constraint fails (`browsemuscle`.`bodyweight`, CONSTRAINT `bodyweight_ibfk_3` FOREIGN KEY (`nome_exercicio`) REFERENCES `exercicios` (`nome_exercicio`))',
  sqlState: '23000',
  index: 0,
  sql: "DELETE FROM exercicios WHERE id = '44'"

**Comment by 8fn** [comment]
```
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: ER_ROW_IS_REFERENCED_2: Cannot delete or update a parent row: a foreign key constraint fails (`browsemuscle`.`bodyweight`, CONSTRAINT `bodyweight_ibfk_3` FOREIGN KEY (`nome_exercicio`) REFERENCES `exercicios` (`nome_exercicio`))
    at Query.Sequence._packetToError (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)
    --------------------
    at Protocol._enqueue (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at Connection.query (/home/tanjil/Desktop/BrowseMuscle/node_modules/mysql/lib/Connection.js:198:25)
    at /home/tanjil/Desktop/BrowseMuscle/src/services/ExercicioService.js:65:7
    at new Promise (<anonymous>)
    at Object.apagar (/home/tanjil/Desktop/BrowseMuscle/src/services/ExercicioService.js:64:10)
    at apagar (/home/tanjil/Desktop/BrowseMuscle/src/controllers/ExercicioController.js:101:26)
    at Layer.handle [as handle_request] (/home/tanjil/Desktop/BrowseMuscle/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/tanjil/Desktop/BrowseMuscle/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/home/tanjil/Desktop/BrowseMuscle/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/home/tanjil/Desktop/BrowseMuscle/node_modules/express/lib/router/layer.js:95:5) {
  code: 'ER_ROW_IS_REFERENCED_2',
  errno: 1451,
  sqlMessage: 'Cannot delete or update a parent row: a foreign key constraint fails (`browsemuscle`.`bodyweight`, CONSTRAINT `bodyweight_ibfk_3` FOREIGN KEY (`nome_exercicio`) REFERENCES `exercicios` (`nome_exercicio`))',
  sqlState: '23000',
  index: 0,
  sql: "DELETE FROM exercicios WHERE id = '44'"
}

```

**Comment by 8fn** [comment]
Eliminar todos os dados dependentes

**Comment by 8fn** [comment]
Add cascade

**Comment by 8fn** [comment]
```sql
ALTER TABLE `abdominais`
  ADD CONSTRAINT `abdominais_ibfk_1` FOREIGN KEY (`nome_dificuldade`) REFERENCES `dificuldades` (`nome`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `abdominais_ibfk_2` FOREIGN KEY (`nome_equipamento`) REFERENCES `equipamentos` (`nome`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `abdominais_ibfk_3` FOREIGN KEY (`nome_exercicio`) REFERENCES `exercicios` (`nome_exercicio`) ON DELETE CASCADE ON UPDATE CASCADE,
  ADD CONSTRAINT `abdominais_ibfk_4` FOREIGN KEY (`nome_musculo`) REFERENCES `musculo` (`nome_musculo`) ON DELETE CASCADE;
```

**Comment by 8fn** [comment]
```sql
-- Constraints for table `avancado`
--
ALTER TABLE `avancado`
  ADD CONSTRAINT `avancado_ibfk_1` FOREIGN KEY (`nome_dificuldade`) REFERENCES `dificuldades` (`nome`) ON DELETE CASCADE,
  ADD CONSTRAINT `avancado_ibfk_2` FOREIGN KEY (`nome_equipamento`) REFERENCES `equipamentos` (`nome`) ON DELETE CASCADE,
  ADD CONSTRAINT `avancado_ibfk_3` FOREIGN KEY (`nome_exercicio`) REFERENCES `exercicios` (`nome_exercicio`) ON DELETE CASCADE,
  ADD CONSTRAINT `avancado_ibfk_4` FOREIGN KEY (`nome_musculo`) REFERENCES `musculo` (`nome_musculo`) ON DELETE CASCADE;

--
-- Constraints for table `barra`
--
ALTER TABLE `barra`
  ADD CONSTRAINT `barra_ibfk_1` FOREIGN KEY (`nome_dificuldade`) REFERENCES `dificuldades` (`nome`) ON DELETE CASCADE,
  ADD CONSTRAINT `barra_ibfk_2` FOREIGN KEY (`nome_equipamento`) REFERENCES `equipamentos` (`nome`) ON DELETE CASCADE,
  ADD CONSTRAINT `barra_ibfk_3` FOREIGN KEY (`nome_exercicio`) REFERENCES `exercicios` (`nome_exercicio`) ON DELETE CASCADE,
  ADD CONSTRAINT `barra_ibfk_4` FOREIGN KEY (`nome_musculo`) REFERENCES `musculo` (`nome_musculo`) ON DELETE CASCADE;
```

**Comment by 8fn** [comment]
Constrain
```sql
ON DELETE CASCADE ON UPDATE CASCADE
```
