### ISSUE TITLE
Error: Packets out of order. Got: 0 Expected: 13

### ISSUE THREAD

**Issue by 8fn** [8fn/BrowseMuscle#65]

**Comment by 8fn** [comment]
`con.query('SET GLOBAL interactive_timeout=28800')`

**Comment by 8fn** [comment]
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: Packets out of order. Got: 0 Expected: 12
    at Parser._tryReadPacketHeader (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/protocol/Parser.js:470:15)
    at Parser.write (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/protocol/Parser.js:33:29)
    at Protocol.write (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (events.js:314:20)
    at addChunk (_stream_readable.js:297:12)
    at readableAddChunk (_stream_readable.js:272:9)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
Emitted 'error' event on Connection instance at:
    at Connection._handleProtocolError (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/Connection.js:423:8)
    at Protocol.emit (events.js:314:20)
    at Protocol._delegateError (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/protocol/Protocol.js:398:10)
    at Protocol.handleParserError (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/protocol/Protocol.js:380:10)
    at Parser._tryReadPacketHeader (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/protocol/Parser.js:478:10)
    at Parser.write (/home/ubuntu/Desktop/browsemuscle/node_modules/mysql/lib/protocol/Parser.js:33:29)
    [... lines matching original stack trace ...]
    at Socket.emit (events.js:314:20) {
  code: 'PROTOCOL_PACKETS_OUT_OF_ORDER',
  fatal: true
}

**Comment by 8fn** [comment]
https://github.com/mysqljs/mysql/issues/2534#issuecomment-1000969684

**Comment by 8fn** [comment]
#95

**Comment by 8fn** [comment]
> [mysqljs/mysql#2534 (comment)](https://github.com/mysqljs/mysql/issues/2534#issuecomment-1000969684)

var mysql = require('mysql');
var pool  = mysql.createPool({
  host     : 'example.org',
  user     : 'bob',
  password : 'secret',
  database : 'my_db'
});

pool.getConnection(function(err, connection) {
  // connected! (unless `err` is set)
});
