### ISSUE TITLE
:bug: Error: listen EADDRINUSE: address already in use :::3000

### ISSUE THREAD

**Issue by 8fn** [8fn/BrowseMuscle#99]
```
Error: listen EADDRINUSE: address already in use :::3000
    at Server.setupListenHandle [as _listen2] (node:net:1372:16)
    at listenInCluster (node:net:1420:12)
    at Server.listen (node:net:1508:7)
    at Function.listen (/home/tanjil/Desktop/BrowseMuscle/node_modules/express/lib/application.js:635:24)
    at Object.<anonymous> (/home/tanjil/Desktop/BrowseMuscle/src/server.js:42:8)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1399:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 3000
}
```

**Comment by 8fn** [comment]
```
lsof -i:3000 
kill -9 [PID] 
```
